### ISSUE TITLE
Коментов в Гите нету так что пойдёт и тут)

### ISSUE THREAD

**Issue by syorito-hatsuki** [ArtemOnigiri/4D-Shapes#1]
Шот страшное ты затеял) 2 репозитория подряд и оба на JS. Где же класическая Java и когда ожидать мобильный кодинг?)

**Comment by uwuzote** [comment]
Оо, нас ждёт веб в 4д

**Comment by ArtemOnigiri** [comment]
JS удобен тем, что можно сразу открыть результат в github-pages

**Comment by syorito-hatsuki** [comment]
> JS удобен тем, что можно сразу открыть результат в github-pages

Рисик, а создай репозиторий со своим логином)
А если интересует говно код, то зацени мой🤣👍

А если по теме, то плюсы на этом кончаются?) Вроде же как Typescript лучше JS😁

**Comment by ArtemOnigiri** [comment]
> А если по теме, то плюсы на этом кончаются?) Вроде же как Typescript лучше JS😁

Typescript лучше в крупных проектах, чтобы код статически проверялся, и избежать внезапных багов. А так он же все равно в JS собирается

**Comment by koto-games** [comment]
👍👍👍
